### ISSUE TITLE
issue with array higher order functions?

### ISSUE THREAD

**Issue by angus-c** [toolness/slowmo-js#5] opened 2013-03-07 18:02 UTC
The following code generates the message _TypeError: Array.prototype.map called on null or undefined_

``` js
var a = [1,2,3,4,5];
var square = function(n) {return n * n};
a.map(square);
```

**Comment by michaelficarra** [comment] 2013-03-07 18:04
Duplicate of #4.

**Comment by toolness** [comment] 2013-05-12 13:21
Thanks for the report! I think I've fixed the bug.

**Closed as completed by toolness** 2013-05-12 13:21 UTC
